services:
  kafka-service:
    build:
      context: ./kafka-service
    container_name: kafka-service
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=http://redis-service:3002
    networks:
      - task-network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - task-network
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - task-network
  redis-service:
    build:
      context: ./redis-service
    container_name: redis-service
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - task-network
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - task-network
  task-service:
    build:
      context: ./task-service
    container_name: task-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=task_management
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345678
      - REDIS_URL=http://redis-service:3002
      - NEXT_APP_URL=http://frontend:5000
      - KAFKA_BROKER=kafka:9092
    networks:
      - task-network
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=task_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
    networks:
      - task-network
  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - task-service
    environment:
      - NEXT_PUBLIC_TASK_SERVICE_URL=http://localhost:3000
    networks:
      - task-network
networks:
  task-network:
    driver: bridge